[build]
  functions = "netlify/functions"
  publish = "public"
  command = "npm run build"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  publish = "public"

[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  force = true
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.14.0"