[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/error.html"
  status = 404

[build.environment]
  NODE_VERSION = "18.14.0"